### ISSUE TITLE
Onboarding wizard

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/Gramps.js#76]
It would be nice having an onboarding wizard that allows uploading a family tree, media, and creating an admin account. It would require the following steps.

- [x] Detect that onboarding is necessary (depends on implementation in backend)
- [x] Show admin user creation form and create user on submit (backend: https://github.com/gramps-project/gramps-webapi/issues/288)
- [x] Show family tree upload form and upload to import endpoint (backend: https://github.com/gramps-project/gramps-webapi/issues/287)
- [x] Allow configuring e-mail credentials for e-mail notifications (backend: https://github.com/gramps-project/gramps-webapi/issues/294)
